In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import joblib

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.naive_bayes import GaussianNB

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score

In [2]:
df = sns.load_dataset("tips")
df.drop(columns=["day"], inplace=True)
df.head()

   total_bill   tip     sex smoker    time  size
0       16.99  1.01  Female     No  Dinner     2
1       10.34  1.66    Male     No  Dinner     3
2       21.01  3.50    Male     No  Dinner     3
3       23.68  3.31    Male     No  Dinner     2
4       24.59  3.61  Female     No  Dinner     4

In [3]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
time          0
size          0
dtype: int64

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   time        244 non-null    category
 5   size        244 non-null    int64
dtypes: category(3), float64(2), int64(1)
memory usage: 6.9 KB

In [5]:
cat_col = df.select_dtypes(include="category")
num_col = df.select_dtypes(include=["int64", "float64"])

In [6]:
for i in cat_col:
    le = LabelEncoder()
    df[i] = le.fit_transform(df[i])
    joblib.dump(le, f"le_{i}.pkl")

In [7]:
x = df.drop(columns=["smoker"])
y = df["smoker"]

In [8]:
x

     total_bill   tip  sex  time  size
0         16.99  1.01    0     0     2
1         10.34  1.66    1     0     3
2         21.01  3.50    1     0     3
3         23.68  3.31    1     0     2
4         24.59  3.61    0     0     4
..          ...   ...  ...   ...   ...
239       29.03  5.92    1     0     3
240       27.18  2.00    0     0     2
241       22.67  2.00    1     0     2
242       17.82  1.75    1     0     2
243       18.78  3.00    0     0     2

[244 rows x 5 columns]

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [10]:
models = {

    "Logistic Regression": LogisticRegression(),

    "Decision Tree": DecisionTreeClassifier(max_depth=20),

    "Random Forest": RandomForestClassifier(n_estimators=50, max_depth=20, max_features="sqrt"),

    "Naive Bayes": GaussianNB(),

    "SVC" : SVC(kernel="linear", C=1.0),

    "KNN" : KNeighborsClassifier(n_neighbors=5)

}

In [11]:
results = {}

In [12]:
for name, i in models.items():
    i.fit(x_train, y_train)
    y_pred = i.predict(x_test)
    results[name] = accuracy_score(y_test, y_pred)
    print(name, accuracy_score(y_test, y_pred))

Logistic Regression 0.6326530612244898
Decision Tree 0.5918367346938775
Random Forest 0.5714285714285714
Naive Bayes 0.6326530612244898
SVC 0.6326530612244898
KNN 0.5714285714285714

In [13]:
best_model_name = max(results, key=results.get)
best_model = models[best_model_name]

In [14]:
joblib.dump(best_model, "best_model.pkl")

['best_model.pkl']